import { Router, type IRouter } from "express";
import healthRouter from "./health";
import casesRouter from "./cases";
import documentsRouter from "./documents";
import aiTasksRouter from "./aiTasks";
import usersRouter from "./users";
import messagesRouter from "./messages";
import billingRouter from "./billing";
import dashboardRouter from "./dashboard";
import aiChatRouter from "./aiChat";
import rbacRouter from "./rbac";
import opponentSimulatorRouter from "./opponentSimulator";
import contractsRouter from "./contracts";
import clientsRouter from "./clients";
import aiAgentsRouter from "./aiAgents";
import commandCenterRouter from "./commandCenter";
import legalResearchRouter from "./legalResearch";
import arbitrationRouter from "./arbitration";
import hrRouter from "./hr";

const router: IRouter = Router();

router.use(healthRouter);
router.use(casesRouter);
router.use(documentsRouter);
router.use(aiTasksRouter);
router.use(usersRouter);
router.use(messagesRouter);
router.use(billingRouter);
router.use(dashboardRouter);
router.use(aiChatRouter);
router.use(rbacRouter);
router.use(opponentSimulatorRouter);
router.use(contractsRouter);
router.use(clientsRouter);
router.use(aiAgentsRouter);
router.use(commandCenterRouter);
router.use(legalResearchRouter);
router.use(arbitrationRouter);
router.use(hrRouter);

export default router;
