import { Router, type IRouter } from "express";
import healthRouter from "./health";
import casesRouter from "./cases";
import documentsRouter from "./documents";
import aiTasksRouter from "./aiTasks";
import usersRouter from "./users";
import messagesRouter from "./messages";
import billingRouter from "./billing";
import dashboardRouter from "./dashboard";
import aiChatRouter from "./aiChat";
import rbacRouter from "./rbac";
import opponentSimulatorRouter from "./opponentSimulator";
import contractsRouter from "./contracts";
import clientsRouter from "./clients";
import aiAgentsRouter from "./aiAgents";
import commandCenterRouter from "./commandCenter";
import legalResearchRouter from "./legalResearch";
import arbitrationRouter from "./arbitration";
import hrRouter from "./hr";
import brandingRouter from "./branding";
import storageRouter from "./storage";
import judgePrepRouter from "./judgePrep";
import webhookRouter from "./webhook";
import invoicesRouter from "./invoices";
import emailRouter from "./email";
import officeRouter from "./office";
import adminRouter from "./admin";
import calendarRouter from "./calendar";
import clientPortalRouter from "./client-portal";
import marketplaceRouter from "./marketplace";
import aiWorkflowRouter from "./ai-workflow";
import firmAdminRouter from "./firm-admin";
import notificationsRouter from "./notifications";
import complianceRouter from "./compliance";
import aiAgentRouter from "./ai-agent";
import aiEngineRouter from "./ai-engine";
import internalMessagesRouter from "./internal-messages";
import aiAssistantRouter from "./ai-assistant";
import subscriptionRouter from "./subscription";
import backupRouter from "./backup";
import accountingRouter from "./accounting";
import developerRouter from "./developer";
import paymentsRouter from "./payments";
import hostingRouter from "./hosting";
import studioRouter from "./studio";
import entitlementsRouter from "./entitlements";
import officeApiKeysRouter from "./officeApiKeys";
import loginTrackingRouter from "./loginTracking";
import financialIntelligenceRouter from "./financialIntelligence";
import remindersRouter from "./reminders";
import emailNotificationsRouter from "./emailNotifications";
import onboardingRouter from "./onboarding";
import importDataRouter from "./importData";
import whatsappRouter from "./whatsapp";

const router: IRouter = Router();

router.use(healthRouter);
router.use(casesRouter);
router.use(documentsRouter);
router.use(aiTasksRouter);
router.use(usersRouter);
router.use(messagesRouter);
router.use(billingRouter);
router.use(dashboardRouter);
router.use(aiChatRouter);
router.use(rbacRouter);
router.use(opponentSimulatorRouter);
router.use(contractsRouter);
router.use(clientsRouter);
router.use(aiAgentsRouter);
router.use(commandCenterRouter);
router.use(legalResearchRouter);
router.use(arbitrationRouter);
router.use(hrRouter);
router.use(brandingRouter);
router.use(storageRouter);
router.use(judgePrepRouter);
router.use(webhookRouter);
router.use(invoicesRouter);
router.use(emailRouter);
router.use(officeRouter);
router.use(adminRouter);
router.use(calendarRouter);
router.use(clientPortalRouter);
router.use(marketplaceRouter);
router.use(aiWorkflowRouter);
router.use(firmAdminRouter);
router.use(notificationsRouter);
router.use(complianceRouter);
router.use(aiAgentRouter);
router.use(aiEngineRouter);
router.use("/internal-messages", internalMessagesRouter);
router.use("/ai-assistant", aiAssistantRouter);
router.use(subscriptionRouter);
router.use(backupRouter);
router.use(accountingRouter);
router.use(developerRouter);
router.use(paymentsRouter);
router.use(hostingRouter);
router.use(studioRouter);
router.use(entitlementsRouter);
router.use(officeApiKeysRouter);
router.use(loginTrackingRouter);
router.use(financialIntelligenceRouter);
router.use(remindersRouter);
router.use(emailNotificationsRouter);
router.use(onboardingRouter);
router.use(importDataRouter);
router.use(whatsappRouter);

export default router;
