import { Router } from "express";

const router = Router();

const PLATFORM_MODULES = [
  {
    id: "cases",
    group: "core",
    title: "إدارة القضايا",
    description: "تتبع كامل لمراحل القضية من الفتح حتى الإغلاق مع جدولة الجلسات والمستندات",
    route: "/cases",
    icon: "Scale",
    color: "#C9A84C",
    enabled: true,
    badge: null,
  },
  {
    id: "clients",
    group: "core",
    title: "إدارة الموكلين (CRM)",
    description: "قاعدة بيانات شاملة للموكلين مع تاريخ القضايا والفواتير وتقييمات الرضا",
    route: "/clients",
    icon: "Users",
    color: "#818CF8",
    enabled: true,
    badge: null,
  },
  {
    id: "contracts",
    group: "core",
    title: "العقود والاتفاقيات",
    description: "إنشاء وتوقيع وأرشفة العقود القانونية وعقود الأتعاب مع تنبيهات الانتهاء",
    route: "/contracts",
    icon: "FileCheck",
    color: "#34D399",
    enabled: true,
    badge: null,
  },
  {
    id: "documents",
    group: "core",
    title: "إدارة المستندات",
    description: "رفع ومعالجة ملفات PDF/DOC مع OCR عربي وتصنيف ذكي تلقائي",
    route: "/documents",
    icon: "FileText",
    color: "#60A5FA",
    enabled: true,
    badge: null,
  },
  {
    id: "calendar",
    group: "core",
    title: "المواعيد والجلسات",
    description: "جدول موحد لجلسات المحاكم والمواعيد مع تنبيهات تلقائية قبل الموعد",
    route: "/calendar",
    icon: "Calendar",
    color: "#F472B6",
    enabled: true,
    badge: null,
  },
  {
    id: "invoices",
    group: "finance",
    title: "الفواتير والأتعاب",
    description: "إصدار فواتير احترافية مع دعم VAT وتتبع المدفوعات وإرسال تذكيرات تلقائية",
    route: "/invoices",
    icon: "Receipt",
    color: "#FBBF24",
    enabled: true,
    badge: null,
  },
  {
    id: "accounting",
    group: "finance",
    title: "المحاسبة والمالية",
    description: "إيرادات ومصاريف وحسابات بنكية وسلف مع تقارير الربح والخسارة",
    route: "/accounting/revenues",
    icon: "TrendingUp",
    color: "#34D399",
    enabled: true,
    badge: null,
  },
  {
    id: "finance-center",
    group: "finance",
    title: "مركز التحصيل المالي",
    description: "متابعة المستحقات المتأخرة وإرسال تذكيرات ذكية وخطط التحصيل",
    route: "/finance",
    icon: "DollarSign",
    color: "#F87171",
    enabled: true,
    badge: "جديد",
  },
  {
    id: "payments",
    group: "finance",
    title: "مركز المدفوعات",
    description: "استقبال مدفوعات الموكلين عبر Stripe مع لوحة تتبع المعاملات",
    route: "/payment-center",
    icon: "CreditCard",
    color: "#818CF8",
    enabled: true,
    badge: null,
  },
  {
    id: "hr",
    group: "team",
    title: "الموارد البشرية",
    description: "إدارة الموظفين والرواتب والإجازات والهيكل التنظيمي للمكتب",
    route: "/employees",
    icon: "UserCircle",
    color: "#FB923C",
    enabled: true,
    badge: null,
  },
  {
    id: "hr-center",
    group: "team",
    title: "مركز الأداء والحوافز",
    description: "تقييمات أداء الموظفين والحوافز والخطط التطويرية السنوية",
    route: "/hr-center",
    icon: "Award",
    color: "#FBBF24",
    enabled: true,
    badge: null,
  },
  {
    id: "messages",
    group: "communication",
    title: "المراسلات الداخلية",
    description: "تواصل فوري بين أعضاء الفريق مع ربط الرسائل بالقضايا والملفات",
    route: "/messages",
    icon: "MessageSquare",
    color: "#34D399",
    enabled: true,
    badge: null,
  },
  {
    id: "client-portal",
    group: "communication",
    title: "بوابة الموكلين",
    description: "رابط مخصص لكل موكل للاطلاع على قضاياه ومستنداته وفواتيره بأمان",
    route: "/client-portal",
    icon: "Globe",
    color: "#818CF8",
    enabled: true,
    badge: null,
  },
  {
    id: "ai-hub",
    group: "ai",
    title: "مساعد AI القانوني",
    description: "محادثة ذكية مع قاعدة معرفة قانونية سعودية + تحليل القضايا والعقود",
    route: "/ai-hub",
    icon: "Bot",
    color: "#A78BFA",
    enabled: true,
    badge: "AI",
  },
  {
    id: "legal-ai",
    group: "ai",
    title: "محرك توليد الوثائق",
    description: "توليد تلقائي لـ 11 نوع وثيقة قانونية: مذكرات، عقود، توكيلات، شكاوى",
    route: "/legal-ai",
    icon: "Sparkles",
    color: "#C9A84C",
    enabled: true,
    badge: "AI",
  },
  {
    id: "legal-research",
    group: "ai",
    title: "البحث القانوني الذكي",
    description: "بحث في الأنظمة واللوائح والسوابق القضائية السعودية بالذكاء الاصطناعي",
    route: "/legal-research",
    icon: "Search",
    color: "#60A5FA",
    enabled: true,
    badge: "AI",
  },
  {
    id: "opponent-simulator",
    group: "ai",
    title: "محاكي الخصم",
    description: "اختبر حججك القانونية أمام محامي AI يمثل الخصم لاكتشاف نقاط الضعف",
    route: "/opponent",
    icon: "Shield",
    color: "#F87171",
    enabled: true,
    badge: "AI",
  },
  {
    id: "analytics",
    group: "insights",
    title: "التحليلات والتقارير",
    description: "تقارير أداء المكتب والإيرادات والقضايا مع رسوم بيانية تفاعلية",
    route: "/analytics",
    icon: "BarChart3",
    color: "#34D399",
    enabled: true,
    badge: null,
  },
  {
    id: "ai-analytics",
    group: "insights",
    title: "التحليل الذكي بـ AI",
    description: "تقرير سردي يومي يحلّل أداء مكتبك ويكشف الفرص والمخاطر تلقائياً",
    route: "/analytics",
    icon: "Brain",
    color: "#A78BFA",
    enabled: true,
    badge: "AI",
  },
  {
    id: "audit-logs",
    group: "insights",
    title: "سجل المراقبة والأمان",
    description: "تتبع كل عملية في النظام مع كشف تلقائي للنشاط المشبوه وتنبيهات أمنية",
    route: "/audit-logs",
    icon: "Activity",
    color: "#F87171",
    enabled: true,
    badge: null,
  },
  {
    id: "arbitration",
    group: "legal",
    title: "التحكيم التجاري",
    description: "إدارة ملفات التحكيم والوساطة خارج المحاكم مع تتبع المراحل",
    route: "/arbitration",
    icon: "Landmark",
    color: "#FBBF24",
    enabled: true,
    badge: null,
  },
  {
    id: "marketplace",
    group: "legal",
    title: "السوق القانوني",
    description: "تواصل مع محامين ومستشارين لتعاون مهني وتحويل القضايا",
    route: "/marketplace",
    icon: "Store",
    color: "#FB923C",
    enabled: true,
    badge: null,
  },
  {
    id: "compliance",
    group: "legal",
    title: "الالتزام والامتثال",
    description: "ضمان التزام المكتب بالمعايير التنظيمية ومتابعة مواعيد الترخيص",
    route: "/compliance",
    icon: "CheckSquare",
    color: "#34D399",
    enabled: true,
    badge: null,
  },
  {
    id: "storage",
    group: "system",
    title: "مدير التخزين",
    description: "إدارة مساحة التخزين السحابي للملفات والمستندات مع تتبع الاستهلاك",
    route: "/storage-settings",
    icon: "HardDrive",
    color: "#60A5FA",
    enabled: true,
    badge: null,
  },
  {
    id: "branding",
    group: "system",
    title: "الهوية والتخصيص",
    description: "تخصيص شعار وألوان وقوالب الفواتير والعلامة التجارية للمكتب",
    route: "/branding",
    icon: "Palette",
    color: "#F472B6",
    enabled: true,
    badge: null,
  },
  {
    id: "studio",
    group: "system",
    title: "الاستوديو (Low-code)",
    description: "بناء جداول وفورمات مخصصة وسير عمل تلقائية بدون كود",
    route: "/studio",
    icon: "Layers",
    color: "#A78BFA",
    enabled: true,
    badge: "متقدم",
  },
];

const MODULE_GROUPS: Record<string, { label: string; color: string }> = {
  core:          { label: "القضايا والموكلون",     color: "#C9A84C" },
  finance:       { label: "المالية والفواتير",      color: "#34D399" },
  team:          { label: "الفريق والموارد البشرية",color: "#FB923C" },
  communication: { label: "التواصل والبوابات",      color: "#818CF8" },
  ai:            { label: "الذكاء الاصطناعي",      color: "#A78BFA" },
  insights:      { label: "التحليلات والمراقبة",   color: "#60A5FA" },
  legal:         { label: "الخدمات القانونية",      color: "#FBBF24" },
  system:        { label: "إعدادات النظام",         color: "#F472B6" },
};

router.get("/platform/modules", (_req, res) => {
  res.json({
    modules: PLATFORM_MODULES,
    groups: MODULE_GROUPS,
    total: PLATFORM_MODULES.length,
    stats: {
      totalModules: PLATFORM_MODULES.length,
      aiPowered: PLATFORM_MODULES.filter(m => m.badge === "AI").length,
      groups: Object.keys(MODULE_GROUPS).length,
    },
  });
});

export default router;
