// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/clean/DarkPremium.tsx": () => import("../components/mockups/clean/DarkPremium.tsx"),
  "./components/mockups/clean/SpurStyle.tsx": () => import("../components/mockups/clean/SpurStyle.tsx"),
  "./components/mockups/landing/BentoGlass.tsx": () => import("../components/mockups/landing/BentoGlass.tsx"),
  "./components/mockups/landing/DarkCinematic.tsx": () => import("../components/mockups/landing/DarkCinematic.tsx"),
  "./components/mockups/landing/PremiumRefined.tsx": () => import("../components/mockups/landing/PremiumRefined.tsx")
};
