/**
 * Central Route Registry — عدالة AI Platform
 * المرجع الوحيد لجميع Routes في المنصة
 *
 * الإضافة: عند إضافة Route جديد يجب:
 *  1. تسجيله هنا أولاً
 *  2. إضافته في App.tsx
 *  3. إضافة رابطه في layout.tsx أو mobile-nav.tsx إذا لزم
 *
 * Justice Legal World Model (JLWM) — internal name preserved
 */

export type RouteGuard =
  | "public"      // لا يتطلب تسجيل دخول
  | "protected"   // يتطلب مستخدماً مسجلاً
  | "workspace"   // يتطلب مستخدماً مع مكتب نشط
  | "admin"       // يتطلب super_admin
  | "role"        // يتطلب صلاحية محددة (RBAC)
  | "redirect";   // Alias يحوّل لمسار آخر

export type RouteModule =
  | "landing"
  | "auth"
  | "portal"
  | "firms"
  | "legal-core"
  | "documents"
  | "ai"
  | "jlwm"
  | "financial"
  | "hr"
  | "communications"
  | "settings"
  | "platform-admin"
  | "analytics"
  | "compliance"
  | "bankruptcy";

export interface RouteDefinition {
  path: string;
  nameAr: string;
  nameInternal: string;
  guard: RouteGuard;
  module: RouteModule;
  permission?: string;
  feature?: string;
  subscription?: string;
  navGroup?: string;
  breadcrumb?: string;
  redirectTo?: string;
  isAlias?: boolean;
  isDynamic?: boolean;
  tags?: string[];
}

export const ROUTE_REGISTRY: RouteDefinition[] = [

  /* ═══════════════════════════════════════════════════════════
     PUBLIC — لا يتطلب تسجيل دخول
  ═══════════════════════════════════════════════════════════ */
  {
    path: "/",
    nameAr: "الصفحة الرئيسية",
    nameInternal: "landing",
    guard: "public",
    module: "landing",
    breadcrumb: "الرئيسية",
  },
  {
    path: "/pricing",
    nameAr: "التسعير والباقات",
    nameInternal: "pricing",
    guard: "public",
    module: "landing",
    breadcrumb: "التسعير",
    navGroup: "landing",
  },
  {
    path: "/demo",
    nameAr: "التجربة التفاعلية",
    nameInternal: "demo",
    guard: "public",
    module: "landing",
    breadcrumb: "تجربة مجانية",
  },
  {
    path: "/demo-login",
    nameAr: "دخول التجربة",
    nameInternal: "demo-login",
    guard: "public",
    module: "landing",
    breadcrumb: "دخول التجربة",
  },
  {
    path: "/live-demo",
    nameAr: "العرض المباشر",
    nameInternal: "live-demo",
    guard: "public",
    module: "landing",
    breadcrumb: "العرض المباشر",
  },
  {
    path: "/terms",
    nameAr: "الشروط والأحكام",
    nameInternal: "terms",
    guard: "public",
    module: "landing",
    breadcrumb: "الشروط والأحكام",
  },
  {
    path: "/privacy",
    nameAr: "سياسة الخصوصية",
    nameInternal: "privacy",
    guard: "public",
    module: "landing",
    breadcrumb: "الخصوصية",
  },
  {
    path: "/security",
    nameAr: "الأمان والحماية",
    nameInternal: "security",
    guard: "public",
    module: "landing",
    breadcrumb: "الأمان",
  },
  {
    path: "/referral",
    nameAr: "برنامج الإحالة",
    nameInternal: "referral",
    guard: "public",
    module: "landing",
    breadcrumb: "الإحالة",
  },
  {
    path: "/system-status",
    nameAr: "حالة النظام",
    nameInternal: "system-status",
    guard: "public",
    module: "landing",
    breadcrumb: "حالة النظام",
  },

  /* ── Auth ── */
  {
    path: "/sign-in/*?",
    nameAr: "تسجيل الدخول",
    nameInternal: "sign-in",
    guard: "public",
    module: "auth",
    breadcrumb: "تسجيل الدخول",
  },
  {
    path: "/sign-up/*?",
    nameAr: "إنشاء حساب",
    nameInternal: "sign-up",
    guard: "public",
    module: "auth",
    breadcrumb: "إنشاء حساب",
  },
  {
    path: "/onboarding",
    nameAr: "إعداد المكتب",
    nameInternal: "onboarding",
    guard: "public",
    module: "auth",
    breadcrumb: "إعداد المكتب",
  },
  {
    path: "/2fa-verify",
    nameAr: "التحقق بخطوتين",
    nameInternal: "2fa-verify",
    guard: "public",
    module: "auth",
    breadcrumb: "التحقق",
  },

  /* ── Dynamic Public ── */
  {
    path: "/sign/:token",
    nameAr: "توقيع المستند",
    nameInternal: "sign-document",
    guard: "public",
    module: "documents",
    isDynamic: true,
    breadcrumb: "توقيع المستند",
  },
  {
    path: "/invoice/:token",
    nameAr: "الفاتورة العامة",
    nameInternal: "invoice-public",
    guard: "public",
    module: "financial",
    isDynamic: true,
    breadcrumb: "الفاتورة",
  },

  /* ── Client Portal ── */
  {
    path: "/portal/login",
    nameAr: "دخول بوابة العميل",
    nameInternal: "portal-login",
    guard: "public",
    module: "portal",
    breadcrumb: "بوابة العميل",
  },
  {
    path: "/portal/my-cases",
    nameAr: "قضاياي",
    nameInternal: "portal-my-cases",
    guard: "public",
    module: "portal",
    breadcrumb: "قضاياي",
  },
  {
    path: "/portal/:token",
    nameAr: "بوابة العميل",
    nameInternal: "portal-view",
    guard: "public",
    module: "portal",
    isDynamic: true,
    breadcrumb: "بوابة العميل",
  },

  /* ── Firm Public Pages ── */
  {
    path: "/firms/:slug",
    nameAr: "صفحة المكتب",
    nameInternal: "firm-page",
    guard: "public",
    module: "firms",
    isDynamic: true,
    breadcrumb: "المكتب",
  },
  {
    path: "/firms/:slug/login",
    nameAr: "دخول المكتب",
    nameInternal: "firm-login",
    guard: "public",
    module: "firms",
    isDynamic: true,
    breadcrumb: "دخول",
  },
  {
    path: "/firms/:slug/store",
    nameAr: "متجر المكتب",
    nameInternal: "firm-store",
    guard: "public",
    module: "firms",
    isDynamic: true,
    breadcrumb: "المتجر",
    feature: "serviceStore",
  },
  {
    path: "/firms/:slug/book",
    nameAr: "حجز موعد",
    nameInternal: "firm-book",
    guard: "public",
    module: "firms",
    isDynamic: true,
    breadcrumb: "حجز موعد",
  },
  {
    path: "/firms/:slug/bankruptcy",
    nameAr: "إفلاس المكتب",
    nameInternal: "firm-bankruptcy",
    guard: "public",
    module: "firms",
    isDynamic: true,
    breadcrumb: "الإفلاس",
  },
  {
    path: "/firms/:slug/service/:serviceId",
    nameAr: "خدمة المكتب",
    nameInternal: "firm-service",
    guard: "public",
    module: "firms",
    isDynamic: true,
    breadcrumb: "الخدمة",
  },

  /* ═══════════════════════════════════════════════════════════
     WORKSPACE — مستخدم مع مكتب نشط
  ═══════════════════════════════════════════════════════════ */
  {
    path: "/dashboard",
    nameAr: "لوحة التحكم",
    nameInternal: "dashboard",
    guard: "workspace",
    module: "legal-core",
    navGroup: "main",
    breadcrumb: "لوحة التحكم",
    tags: ["home", "main"],
  },
  {
    path: "/cases",
    nameAr: "القضايا",
    nameInternal: "cases",
    guard: "workspace",
    module: "legal-core",
    navGroup: "legal",
    breadcrumb: "القضايا",
    tags: ["cases", "legal"],
  },
  {
    path: "/cases/:id",
    nameAr: "تفاصيل القضية",
    nameInternal: "case-detail",
    guard: "workspace",
    module: "legal-core",
    isDynamic: true,
    breadcrumb: "تفاصيل القضية",
    tags: ["cases", "legal"],
  },
  {
    path: "/hearings-calendar",
    nameAr: "الجلسات",
    nameInternal: "hearings-calendar",
    guard: "workspace",
    module: "legal-core",
    navGroup: "legal",
    breadcrumb: "الجلسات",
    tags: ["hearings", "calendar"],
  },
  {
    path: "/clients",
    nameAr: "العملاء",
    nameInternal: "clients",
    guard: "workspace",
    module: "legal-core",
    navGroup: "clients",
    breadcrumb: "العملاء",
    tags: ["clients", "crm"],
  },
  {
    path: "/clients/:id",
    nameAr: "ملف العميل",
    nameInternal: "client-detail",
    guard: "workspace",
    module: "legal-core",
    isDynamic: true,
    breadcrumb: "ملف العميل",
    tags: ["clients", "crm"],
  },
  {
    path: "/activity-stream",
    nameAr: "تدفق النشاط",
    nameInternal: "activity-stream",
    guard: "workspace",
    module: "analytics",
    breadcrumb: "تدفق النشاط",
  },

  /* ═══════════════════════════════════════════════════════════
     PROTECTED — مستخدم مسجّل
  ═══════════════════════════════════════════════════════════ */

  /* ── Documents ── */
  {
    path: "/documents",
    nameAr: "المستندات",
    nameInternal: "documents",
    guard: "protected",
    module: "documents",
    navGroup: "documents",
    breadcrumb: "المستندات",
  },
  {
    path: "/contracts",
    nameAr: "العقود",
    nameInternal: "contracts",
    guard: "protected",
    module: "documents",
    navGroup: "documents",
    breadcrumb: "العقود",
  },
  {
    path: "/letters",
    nameAr: "المراسلات الرسمية",
    nameInternal: "letters",
    guard: "protected",
    module: "documents",
    navGroup: "documents",
    breadcrumb: "المراسلات الرسمية",
  },
  {
    path: "/warnings",
    nameAr: "الإنذارات",
    nameInternal: "warnings",
    guard: "protected",
    module: "documents",
    navGroup: "documents",
    breadcrumb: "الإنذارات",
  },
  {
    path: "/document-templates",
    nameAr: "النماذج والقوالب",
    nameInternal: "document-templates",
    guard: "protected",
    module: "documents",
    navGroup: "documents",
    breadcrumb: "النماذج",
  },
  {
    path: "/document-center",
    nameAr: "الأرشيف القضائي",
    nameInternal: "document-center",
    guard: "protected",
    module: "documents",
    navGroup: "documents",
    breadcrumb: "الأرشيف",
  },

  /* ── AI Module ── */
  {
    path: "/ai-hub",
    nameAr: "مركز الذكاء",
    nameInternal: "ai-hub",
    guard: "protected",
    module: "ai",
    navGroup: "ai",
    breadcrumb: "مركز الذكاء",
    feature: "ai",
  },
  {
    path: "/ai-coo",
    nameAr: "المدير التنفيذي الذكي",
    nameInternal: "ai-coo",
    guard: "protected",
    module: "ai",
    navGroup: "ai",
    breadcrumb: "المدير الذكي",
    feature: "ai",
  },
  {
    path: "/ai-tasks",
    nameAr: "مهام الذكاء",
    nameInternal: "ai-tasks",
    guard: "protected",
    module: "ai",
    navGroup: "ai",
    breadcrumb: "مهام الذكاء",
  },
  {
    path: "/ai-router",
    nameAr: "موجّه الذكاء",
    nameInternal: "ai-router",
    guard: "protected",
    module: "ai",
    breadcrumb: "موجّه الذكاء",
  },
  {
    path: "/ai-workflow-builder",
    nameAr: "منشئ سير العمل الذكي",
    nameInternal: "ai-workflow-builder",
    guard: "protected",
    module: "ai",
    navGroup: "ai",
    breadcrumb: "سير العمل",
  },
  {
    path: "/legal-ai",
    nameAr: "كتابة المذكرات",
    nameInternal: "legal-ai",
    guard: "protected",
    module: "ai",
    navGroup: "ai",
    breadcrumb: "كتابة المذكرات",
    feature: "ai",
  },
  {
    path: "/opponent-simulator",
    nameAr: "محاكي الخصم",
    nameInternal: "opponent-simulator",
    guard: "protected",
    module: "ai",
    navGroup: "ai",
    breadcrumb: "محاكي الخصم",
    feature: "ai",
  },
  {
    path: "/command-center",
    nameAr: "مركز القيادة",
    nameInternal: "command-center",
    guard: "protected",
    module: "ai",
    breadcrumb: "مركز القيادة",
  },

  /* ── Redirects: AI aliases → /ai-hub ── */
  {
    path: "/ai-copilot",
    nameAr: "المساعد القانوني (إعادة توجيه)",
    nameInternal: "ai-copilot-redirect",
    guard: "redirect",
    module: "ai",
    redirectTo: "/ai-hub",
    isAlias: true,
  },
  {
    path: "/adoul",
    nameAr: "عدول (إعادة توجيه)",
    nameInternal: "adoul-redirect",
    guard: "redirect",
    module: "ai",
    redirectTo: "/ai-hub",
    isAlias: true,
  },
  {
    path: "/ai-chat",
    nameAr: "محادثة الذكاء (إعادة توجيه)",
    nameInternal: "ai-chat-redirect",
    guard: "redirect",
    module: "ai",
    redirectTo: "/ai-hub",
    isAlias: true,
  },
  {
    path: "/ai-agents",
    nameAr: "وكلاء الذكاء (إعادة توجيه)",
    nameInternal: "ai-agents-redirect",
    guard: "redirect",
    module: "ai",
    redirectTo: "/ai-hub",
    isAlias: true,
  },
  {
    path: "/ai-assistant",
    nameAr: "مساعد الذكاء (إعادة توجيه)",
    nameInternal: "ai-assistant-redirect",
    guard: "redirect",
    module: "ai",
    redirectTo: "/ai-hub",
    isAlias: true,
  },

  /* ── JLWM — مركز القيادة القانونية ── */
  {
    path: "/jlwm",
    nameAr: "مركز القيادة القانونية",
    nameInternal: "jlwm-dashboard",
    guard: "protected",
    module: "jlwm",
    navGroup: "jlwm",
    breadcrumb: "مركز القيادة القانونية",
  },
  {
    path: "/jlwm/command",
    nameAr: "مركز القيادة الذكي",
    nameInternal: "jlwm-command",
    guard: "protected",
    module: "jlwm",
    navGroup: "jlwm",
    breadcrumb: "القيادة الذكية",
  },
  {
    path: "/jlwm/world-state",
    nameAr: "حالة العالم القانوني",
    nameInternal: "jlwm-world-state",
    guard: "protected",
    module: "jlwm",
    navGroup: "jlwm",
    breadcrumb: "حالة العالم",
  },
  {
    path: "/jlwm/memory-graph",
    nameAr: "مخطط الذاكرة",
    nameInternal: "jlwm-memory-graph",
    guard: "protected",
    module: "jlwm",
    navGroup: "jlwm",
    breadcrumb: "مخطط الذاكرة",
  },
  {
    path: "/jlwm/predictions",
    nameAr: "التنبؤات والتوصيات",
    nameInternal: "jlwm-predictions",
    guard: "protected",
    module: "jlwm",
    navGroup: "jlwm",
    breadcrumb: "التنبؤات",
  },
  {
    path: "/jlwm/future-explorer",
    nameAr: "مستكشف المستقبل",
    nameInternal: "jlwm-future-explorer",
    guard: "protected",
    module: "jlwm",
    navGroup: "jlwm",
    breadcrumb: "مستكشف المستقبل",
  },
  {
    path: "/jlwm/simulation",
    nameAr: "النسخ الرقمية والمحاكاة",
    nameInternal: "jlwm-simulation",
    guard: "protected",
    module: "jlwm",
    navGroup: "jlwm",
    breadcrumb: "المحاكاة",
  },
  {
    path: "/jlwm/litigation-intelligence",
    nameAr: "ذكاء التقاضي",
    nameInternal: "jlwm-litigation-intelligence",
    guard: "protected",
    module: "jlwm",
    navGroup: "jlwm",
    breadcrumb: "ذكاء التقاضي",
  },
  {
    path: "/jlwm/prediction-accuracy",
    nameAr: "دقة التنبؤ",
    nameInternal: "jlwm-prediction-accuracy",
    guard: "protected",
    module: "jlwm",
    navGroup: "jlwm",
    breadcrumb: "دقة التنبؤ",
  },
  {
    path: "/jlwm/executive-intelligence",
    nameAr: "الذكاء التنفيذي",
    nameInternal: "jlwm-executive-intelligence",
    guard: "protected",
    module: "jlwm",
    navGroup: "jlwm",
    breadcrumb: "الذكاء التنفيذي",
  },
  {
    path: "/jlwm/legal-coo",
    nameAr: "المدير التشغيلي القانوني",
    nameInternal: "jlwm-legal-coo",
    guard: "protected",
    module: "jlwm",
    navGroup: "jlwm",
    breadcrumb: "المدير التشغيلي",
  },
  {
    path: "/jlwm/reliability",
    nameAr: "الموثوقية والثقة",
    nameInternal: "jlwm-reliability",
    guard: "protected",
    module: "jlwm",
    navGroup: "jlwm",
    breadcrumb: "الموثوقية",
  },
  {
    path: "/jlwm/enterprise",
    nameAr: "التقرير المؤسسي الشامل",
    nameInternal: "jlwm-enterprise",
    guard: "protected",
    module: "jlwm",
    navGroup: "jlwm",
    breadcrumb: "التقرير المؤسسي",
  },

  /* ── Legal Specializations ── */
  {
    path: "/legal-research",
    nameAr: "البحث القانوني",
    nameInternal: "legal-research",
    guard: "protected",
    module: "legal-core",
    navGroup: "legal",
    breadcrumb: "البحث القانوني",
  },
  {
    path: "/arbitration",
    nameAr: "التحكيم",
    nameInternal: "arbitration",
    guard: "protected",
    module: "legal-core",
    navGroup: "legal",
    breadcrumb: "التحكيم",
  },
  {
    path: "/judge-prep",
    nameAr: "التحضير للجلسة",
    nameInternal: "judge-prep",
    guard: "protected",
    module: "legal-core",
    navGroup: "legal",
    breadcrumb: "التحضير للجلسة",
  },
  {
    path: "/saudi-systems",
    nameAr: "الأنظمة السعودية",
    nameInternal: "saudi-systems",
    guard: "protected",
    module: "legal-core",
    navGroup: "legal",
    breadcrumb: "الأنظمة السعودية",
  },
  {
    path: "/mediators",
    nameAr: "الوسطاء والوكلاء",
    nameInternal: "mediators",
    guard: "protected",
    module: "legal-core",
    navGroup: "clients",
    breadcrumb: "الوسطاء",
  },
  {
    path: "/risk-management",
    nameAr: "إدارة المخاطر",
    nameInternal: "risk-management",
    guard: "protected",
    module: "compliance",
    navGroup: "compliance",
    breadcrumb: "المخاطر",
  },
  {
    path: "/compliance",
    nameAr: "الامتثال",
    nameInternal: "compliance",
    guard: "protected",
    module: "compliance",
    navGroup: "compliance",
    breadcrumb: "الامتثال",
  },
  {
    path: "/legal-os",
    nameAr: "نظام التشغيل القانوني",
    nameInternal: "legal-os",
    guard: "protected",
    module: "legal-core",
    breadcrumb: "نظام التشغيل",
  },

  /* ── Financial ── */
  {
    path: "/invoices",
    nameAr: "الفواتير",
    nameInternal: "invoices",
    guard: "protected",
    module: "financial",
    navGroup: "financial",
    breadcrumb: "الفواتير",
  },
  {
    path: "/revenues",
    nameAr: "الإيرادات",
    nameInternal: "revenues",
    guard: "protected",
    module: "financial",
    navGroup: "financial",
    breadcrumb: "الإيرادات",
    permission: "financial:view",
  },
  {
    path: "/expenses",
    nameAr: "المصروفات",
    nameInternal: "expenses",
    guard: "protected",
    module: "financial",
    navGroup: "financial",
    breadcrumb: "المصروفات",
    permission: "financial:view",
  },
  {
    path: "/financial-reports",
    nameAr: "التقارير المالية",
    nameInternal: "financial-reports",
    guard: "protected",
    module: "financial",
    navGroup: "financial",
    breadcrumb: "التقارير المالية",
  },
  {
    path: "/financial-statements",
    nameAr: "القوائم المالية",
    nameInternal: "financial-statements",
    guard: "protected",
    module: "financial",
    navGroup: "financial",
    breadcrumb: "القوائم المالية",
  },
  {
    path: "/cashflow",
    nameAr: "التدفقات النقدية",
    nameInternal: "cashflow",
    guard: "protected",
    module: "financial",
    navGroup: "financial",
    breadcrumb: "التدفقات",
    permission: "financial:view",
  },
  {
    path: "/bank-accounts",
    nameAr: "الحسابات البنكية",
    nameInternal: "bank-accounts",
    guard: "protected",
    module: "financial",
    navGroup: "financial",
    breadcrumb: "البنوك",
    permission: "financial:view",
  },
  {
    path: "/advances",
    nameAr: "السُّلف",
    nameInternal: "advances",
    guard: "protected",
    module: "financial",
    navGroup: "financial",
    breadcrumb: "السُّلف",
    permission: "financial:view",
  },
  {
    path: "/tax-settings",
    nameAr: "الضرائب",
    nameInternal: "tax-settings",
    guard: "protected",
    module: "financial",
    navGroup: "financial",
    breadcrumb: "الضرائب",
    permission: "financial:view",
  },
  {
    path: "/payment-center",
    nameAr: "مركز المدفوعات",
    nameInternal: "payment-center",
    guard: "protected",
    module: "financial",
    navGroup: "financial",
    breadcrumb: "المدفوعات",
  },
  {
    path: "/finance",
    nameAr: "مركز المالية",
    nameInternal: "finance",
    guard: "protected",
    module: "financial",
    navGroup: "financial",
    breadcrumb: "المالية",
  },
  {
    path: "/collections",
    nameAr: "التحصيل",
    nameInternal: "collections",
    guard: "protected",
    module: "financial",
    navGroup: "financial",
    breadcrumb: "التحصيل",
  },
  {
    path: "/financial-intelligence",
    nameAr: "الذكاء المالي",
    nameInternal: "financial-intelligence",
    guard: "protected",
    module: "financial",
    navGroup: "financial",
    breadcrumb: "الذكاء المالي",
  },
  {
    path: "/enterprise-finance",
    nameAr: "المحاسبة ERP",
    nameInternal: "enterprise-finance",
    guard: "protected",
    module: "financial",
    navGroup: "financial",
    breadcrumb: "المحاسبة ERP",
  },
  {
    path: "/ui-builder",
    nameAr: "منشئ الواجهات",
    nameInternal: "ui-builder",
    guard: "protected",
    module: "ai",
    breadcrumb: "منشئ الواجهات",
  },

  /* ── HR ── */
  {
    path: "/hr",
    nameAr: "الموارد البشرية (إعادة توجيه)",
    nameInternal: "hr-redirect",
    guard: "redirect",
    module: "hr",
    redirectTo: "/hr-center",
    isAlias: true,
  },
  {
    path: "/employees",
    nameAr: "الموظفون",
    nameInternal: "employees",
    guard: "protected",
    module: "hr",
    navGroup: "hr",
    breadcrumb: "الموظفون",
  },
  {
    path: "/attendance",
    nameAr: "الحضور والانصراف",
    nameInternal: "attendance",
    guard: "protected",
    module: "hr",
    navGroup: "hr",
    breadcrumb: "الحضور",
  },
  {
    path: "/leaves",
    nameAr: "الإجازات",
    nameInternal: "leaves",
    guard: "protected",
    module: "hr",
    navGroup: "hr",
    breadcrumb: "الإجازات",
  },
  {
    path: "/payroll",
    nameAr: "الرواتب",
    nameInternal: "payroll",
    guard: "role",
    module: "hr",
    navGroup: "hr",
    breadcrumb: "الرواتب",
    permission: "payroll:view",
  },
  {
    path: "/hr-center",
    nameAr: "مركز الموارد البشرية",
    nameInternal: "hr-center",
    guard: "protected",
    module: "hr",
    navGroup: "hr",
    breadcrumb: "مركز HR",
  },
  {
    path: "/hr-enterprise",
    nameAr: "HR المؤسسي",
    nameInternal: "hr-enterprise",
    guard: "protected",
    module: "hr",
    navGroup: "hr",
    breadcrumb: "HR المؤسسي",
  },
  {
    path: "/hr-systems",
    nameAr: "أنظمة HR",
    nameInternal: "hr-systems",
    guard: "protected",
    module: "hr",
    navGroup: "hr",
    breadcrumb: "أنظمة HR",
  },
  {
    path: "/branches",
    nameAr: "الفروع",
    nameInternal: "branches",
    guard: "protected",
    module: "hr",
    navGroup: "hr",
    breadcrumb: "الفروع",
  },
  {
    path: "/org-structure",
    nameAr: "الهيكل الوظيفي",
    nameInternal: "org-structure",
    guard: "protected",
    module: "hr",
    navGroup: "hr",
    breadcrumb: "الهيكل الوظيفي",
  },

  /* ── Analytics ── */
  {
    path: "/analytics",
    nameAr: "التحليلات",
    nameInternal: "analytics",
    guard: "protected",
    module: "analytics",
    navGroup: "analytics",
    breadcrumb: "التحليلات",
  },
  {
    path: "/tasks",
    nameAr: "المهام",
    nameInternal: "tasks",
    guard: "protected",
    module: "legal-core",
    navGroup: "legal",
    breadcrumb: "المهام",
  },
  {
    path: "/calendar",
    nameAr: "التقويم",
    nameInternal: "calendar",
    guard: "protected",
    module: "legal-core",
    navGroup: "legal",
    breadcrumb: "التقويم",
    feature: "calendar",
  },

  /* ── Communications ── */
  {
    path: "/messages",
    nameAr: "المراسلات",
    nameInternal: "messages",
    guard: "protected",
    module: "communications",
    navGroup: "communications",
    breadcrumb: "المراسلات",
  },
  {
    path: "/reminders",
    nameAr: "التذكيرات",
    nameInternal: "reminders",
    guard: "protected",
    module: "communications",
    navGroup: "communications",
    breadcrumb: "التذكيرات",
  },
  {
    path: "/email-notifications",
    nameAr: "إشعارات البريد",
    nameInternal: "email-notifications",
    guard: "protected",
    module: "communications",
    navGroup: "communications",
    breadcrumb: "البريد",
  },
  {
    path: "/whatsapp-settings",
    nameAr: "واتساب",
    nameInternal: "whatsapp-settings",
    guard: "protected",
    module: "communications",
    navGroup: "communications",
    breadcrumb: "واتساب",
  },
  {
    path: "/telegram-settings",
    nameAr: "تيليجرام",
    nameInternal: "telegram-settings",
    guard: "protected",
    module: "communications",
    navGroup: "communications",
    breadcrumb: "تيليجرام",
  },
  {
    path: "/notification-settings",
    nameAr: "الإشعارات",
    nameInternal: "notification-settings",
    guard: "protected",
    module: "communications",
    navGroup: "communications",
    breadcrumb: "الإشعارات",
  },

  /* ── Bankruptcy ── */
  {
    path: "/bankruptcy",
    nameAr: "الإفلاس",
    nameInternal: "bankruptcy",
    guard: "protected",
    module: "bankruptcy",
    navGroup: "bankruptcy",
    breadcrumb: "الإفلاس",
  },
  {
    path: "/bankruptcy/:section",
    nameAr: "قسم الإفلاس",
    nameInternal: "bankruptcy-section",
    guard: "protected",
    module: "bankruptcy",
    navGroup: "bankruptcy",
    isDynamic: true,
    breadcrumb: "الإفلاس",
  },

  /* ── Settings ── */
  {
    path: "/settings",
    nameAr: "إعدادات المكتب (إعادة توجيه)",
    nameInternal: "settings-redirect",
    guard: "redirect",
    module: "settings",
    redirectTo: "/office-settings",
    isAlias: true,
  },
  {
    path: "/profile",
    nameAr: "الملف الشخصي (إعادة توجيه)",
    nameInternal: "profile-redirect",
    guard: "redirect",
    module: "settings",
    redirectTo: "/my-sessions",
    isAlias: true,
  },
  {
    path: "/help",
    nameAr: "المساعدة (إعادة توجيه)",
    nameInternal: "help-redirect",
    guard: "redirect",
    module: "settings",
    redirectTo: "/firm-admin",
    isAlias: true,
  },
  {
    path: "/office-settings",
    nameAr: "إعدادات المكتب",
    nameInternal: "office-settings",
    guard: "protected",
    module: "settings",
    navGroup: "settings",
    breadcrumb: "الإعدادات",
    permission: "settings:view",
  },
  {
    path: "/office-management",
    nameAr: "إدارة المكتب",
    nameInternal: "office-management",
    guard: "protected",
    module: "settings",
    navGroup: "settings",
    breadcrumb: "إدارة المكتب",
  },
  {
    path: "/website-builder",
    nameAr: "منشئ الموقع",
    nameInternal: "website-builder",
    guard: "protected",
    module: "settings",
    navGroup: "settings",
    breadcrumb: "الموقع الإلكتروني",
  },
  {
    path: "/storage-settings",
    nameAr: "إدارة التخزين",
    nameInternal: "storage-settings",
    guard: "protected",
    module: "settings",
    navGroup: "settings",
    breadcrumb: "التخزين",
  },
  {
    path: "/theme-builder",
    nameAr: "منشئ الثيم",
    nameInternal: "theme-builder",
    guard: "protected",
    module: "settings",
    navGroup: "settings",
    breadcrumb: "الثيم",
  },
  {
    path: "/firm-admin",
    nameAr: "لوحة مدير المكتب",
    nameInternal: "firm-admin",
    guard: "protected",
    module: "settings",
    navGroup: "settings",
    breadcrumb: "مدير المكتب",
  },
  {
    path: "/team",
    nameAr: "فريق العمل",
    nameInternal: "team",
    guard: "protected",
    module: "settings",
    navGroup: "settings",
    breadcrumb: "الفريق",
  },
  {
    path: "/backup",
    nameAr: "النسخ الاحتياطي",
    nameInternal: "backup",
    guard: "protected",
    module: "settings",
    navGroup: "settings",
    breadcrumb: "النسخ الاحتياطي",
  },
  {
    path: "/my-sessions",
    nameAr: "الجلسات والأجهزة",
    nameInternal: "my-sessions",
    guard: "protected",
    module: "settings",
    breadcrumb: "جلساتي",
  },
  {
    path: "/my-profile",
    nameAr: "ملفي الشخصي",
    nameInternal: "my-profile",
    guard: "protected",
    module: "settings",
    breadcrumb: "ملفي",
  },
  {
    path: "/login-tracking",
    nameAr: "سجل تسجيل الدخول",
    nameInternal: "login-tracking",
    guard: "protected",
    module: "settings",
    breadcrumb: "سجل الدخول",
  },
  {
    path: "/2fa-setup",
    nameAr: "إعداد التحقق بخطوتين",
    nameInternal: "2fa-setup",
    guard: "protected",
    module: "settings",
    breadcrumb: "التحقق بخطوتين",
  },
  {
    path: "/billing",
    nameAr: "الاشتراك والباقات",
    nameInternal: "billing",
    guard: "protected",
    module: "settings",
    navGroup: "settings",
    breadcrumb: "الاشتراك",
  },
  {
    path: "/upgrade",
    nameAr: "ترقية الباقة",
    nameInternal: "upgrade",
    guard: "protected",
    module: "settings",
    breadcrumb: "الترقية",
  },
  {
    path: "/support",
    nameAr: "الدعم الفني",
    nameInternal: "support",
    guard: "protected",
    module: "settings",
    breadcrumb: "الدعم",
  },
  {
    path: "/integrations",
    nameAr: "التكاملات",
    nameInternal: "integrations",
    guard: "protected",
    module: "settings",
    navGroup: "settings",
    breadcrumb: "التكاملات",
  },
  {
    path: "/client-portal",
    nameAr: "بوابة العميل",
    nameInternal: "client-portal",
    guard: "protected",
    module: "settings",
    navGroup: "clients",
    breadcrumb: "بوابة العميل",
    feature: "clientPortal",
  },
  {
    path: "/marketplace",
    nameAr: "سوق الخدمات",
    nameInternal: "marketplace",
    guard: "protected",
    module: "settings",
    navGroup: "clients",
    breadcrumb: "سوق الخدمات",
    feature: "serviceStore",
  },

  /* ── RBAC ── */
  {
    path: "/users",
    nameAr: "المستخدمون",
    nameInternal: "users",
    guard: "role",
    module: "settings",
    navGroup: "settings",
    breadcrumb: "المستخدمون",
    permission: "users:view",
  },
  {
    path: "/design-system",
    nameAr: "نظام التصميم",
    nameInternal: "design-system",
    guard: "protected",
    module: "settings",
    breadcrumb: "نظام التصميم",
  },

  /* ═══════════════════════════════════════════════════════════
     ADMIN — Super Admin فقط
  ═══════════════════════════════════════════════════════════ */
  {
    path: "/super-admin",
    nameAr: "إدارة المنصة",
    nameInternal: "super-admin",
    guard: "admin",
    module: "platform-admin",
    navGroup: "platform-admin",
    breadcrumb: "إدارة المنصة",
  },
  {
    path: "/studio",
    nameAr: "الاستوديو",
    nameInternal: "studio",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "الاستوديو",
  },
  {
    path: "/financial-core",
    nameAr: "المحرك المالي",
    nameInternal: "financial-core",
    guard: "admin",
    module: "financial",
    navGroup: "financial",
    breadcrumb: "المحرك المالي",
  },
  {
    path: "/audit-logs",
    nameAr: "سجلات التدقيق",
    nameInternal: "audit-logs",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "سجلات التدقيق",
  },
  {
    path: "/audit-center",
    nameAr: "مركز التدقيق",
    nameInternal: "audit-center",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "مركز التدقيق",
  },
  {
    path: "/soc",
    nameAr: "مركز العمليات الأمنية",
    nameInternal: "soc",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "مركز الأمان",
  },
  {
    path: "/executive-dashboard",
    nameAr: "لوحة القيادة التنفيذية",
    nameInternal: "executive-dashboard",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "القيادة التنفيذية",
  },
  {
    path: "/engineering-center",
    nameAr: "مركز الهندسة",
    nameInternal: "engineering-center",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "مركز الهندسة",
  },
  {
    path: "/ai-command-center",
    nameAr: "مركز قيادة الذكاء",
    nameInternal: "ai-command-center",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "قيادة الذكاء",
  },
  {
    path: "/production-os",
    nameAr: "نظام الإنتاج",
    nameInternal: "production-os",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "نظام الإنتاج",
  },
  {
    path: "/control-tower",
    nameAr: "برج التحكم",
    nameInternal: "control-tower",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "برج التحكم",
  },
  {
    path: "/saas-os",
    nameAr: "نظام SaaS",
    nameInternal: "saas-os",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "SaaS",
  },
  {
    path: "/commercial-launch",
    nameAr: "الإطلاق التجاري",
    nameInternal: "commercial-launch",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "الإطلاق التجاري",
  },
  {
    path: "/monitoring",
    nameAr: "المراقبة",
    nameInternal: "monitoring",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "المراقبة",
  },
  {
    path: "/prevention",
    nameAr: "الوقاية",
    nameInternal: "prevention",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "الوقاية",
  },
  {
    path: "/alerts",
    nameAr: "التنبيهات",
    nameInternal: "alerts",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "التنبيهات",
  },
  {
    path: "/financial-engine",
    nameAr: "المحرك المالي المتقدم",
    nameInternal: "financial-engine",
    guard: "admin",
    module: "financial",
    breadcrumb: "المحرك المالي",
  },
  {
    path: "/finance-dashboard",
    nameAr: "لوحة المالية",
    nameInternal: "finance-dashboard",
    guard: "admin",
    module: "financial",
    breadcrumb: "لوحة المالية",
  },
  {
    path: "/isolation",
    nameAr: "عزل المستأجرين",
    nameInternal: "isolation",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "العزل",
  },
  {
    path: "/hardening",
    nameAr: "تصليب النظام",
    nameInternal: "hardening",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "التصليب",
  },
  {
    path: "/zero-trust",
    nameAr: "الثقة الصفرية",
    nameInternal: "zero-trust",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "الثقة الصفرية",
  },
  {
    path: "/launch-gate",
    nameAr: "بوابة الإطلاق",
    nameInternal: "launch-gate",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "بوابة الإطلاق",
  },
  {
    path: "/production-launch",
    nameAr: "إطلاق الإنتاج",
    nameInternal: "production-launch",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "الإطلاق",
  },
  {
    path: "/self-healing",
    nameAr: "الإصلاح الذاتي",
    nameInternal: "self-healing",
    guard: "admin",
    module: "platform-admin",
    breadcrumb: "الإصلاح الذاتي",
  },
];

/** جميع المسارات الفريدة المسجّلة */
export const REGISTERED_PATHS = new Set(ROUTE_REGISTRY.map(r => r.path));

/** البحث عن Route بمساره */
export function findRoute(path: string): RouteDefinition | undefined {
  return ROUTE_REGISTRY.find(r => r.path === path);
}

/** جميع routes لوحدة معينة */
export function getModuleRoutes(module: RouteModule): RouteDefinition[] {
  return ROUTE_REGISTRY.filter(r => r.module === module);
}

/** جميع routes الظاهرة في التنقل (غير aliases) */
export function getNavRoutes(navGroup: string): RouteDefinition[] {
  return ROUTE_REGISTRY.filter(r => r.navGroup === navGroup && !r.isAlias);
}

/** فحص ما إذا كان مسار مسجّل */
export function isRegisteredPath(path: string): boolean {
  if (REGISTERED_PATHS.has(path)) return true;
  return ROUTE_REGISTRY.some(r => {
    if (!r.isDynamic) return false;
    const pattern = r.path.replace(/:[^/]+/g, "[^/]+");
    return new RegExp(`^${pattern}$`).test(path);
  });
}

/** ملخص إحصائي */
export function getRegistryStats() {
  const stats = {
    total: ROUTE_REGISTRY.length,
    byGuard: {} as Record<RouteGuard, number>,
    byModule: {} as Record<string, number>,
    aliases: ROUTE_REGISTRY.filter(r => r.isAlias).length,
    dynamic: ROUTE_REGISTRY.filter(r => r.isDynamic).length,
    withPermission: ROUTE_REGISTRY.filter(r => r.permission).length,
    withFeatureFlag: ROUTE_REGISTRY.filter(r => r.feature).length,
  };
  for (const r of ROUTE_REGISTRY) {
    stats.byGuard[r.guard] = (stats.byGuard[r.guard] ?? 0) + 1;
    stats.byModule[r.module] = (stats.byModule[r.module] ?? 0) + 1;
  }
  return stats;
}
